[package]
name = "nms_backend"
version = "0.2.0-alpha"
edition = "2024"

[lints.rust]
non_snake_case = "allow"
non_camel_case_types = "allow"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tokio_unstable)'] }

[dependencies]
anyhow = "1.0"
async-recursion = "1.1.1"
async-trait = "0.1"
axum = {version = "0.8.9", features = ["tracing","macros","multipart"] }
axum-auth = "0.8.1"
base64 = "0.23"
chrono = { version = "0.4", features = ["alloc","serde"] }
configparser = {  version = "3.2", features = ["indexmap"] }
console-subscriber = "0.5"
futures = "0.3.33"
indexmap = { version = "2", features = ["serde"] }
inventory = "0.3.24"
ipnet = "2.12"
jsonwebtoken = "9"
psutil = "3.3.0"
regex = "1.0"
reqwest = { version = "0.13", features = ["json","query"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
struct_iterable = {path = "3thparty/rust_struct_iterable/struct_iterable"}
strum = { version = "0.28", features = ["derive"] }
sysinfo = "0.39.6"
tokio = { version = "1", features = ["full","tracing"] }
tokio-stream = { version = "0.1.19", features = ["fs"] }
totp-rs = { version = "5", features = ["otpauth","gen_secret"] }
tower-http = { version = "0.6.1", features = ["trace"] }
tower_governor = "0.8.0"
tracing = "0.1"
tracing-subscriber = "0.3.0"
uuid = { version = "1", features = ["v4"] }
case_insensitive_hashmap = "1.0.1"
tree-ds = "0.2"